-- P124 誰是鄰居｜Who Borders
-- 僅建立 P124 專屬物件，不會修改其他 P 系列專案。

create table if not exists public."TblP124Category" (
  "CategoryID" bigint generated by default as identity primary key,
  "CategoryCode" text not null unique,
  "CategoryNameZh" text not null,
  "CategoryNameEn" text not null,
  "DescriptionZh" text,
  "DescriptionEn" text,
  "Items" jsonb not null default '[]'::jsonb,
  "SortOrder" integer not null default 0,
  "IsActive" boolean not null default true,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "ChkP124CategoryCode" check ("CategoryCode" ~ '^[A-Z0-9_]+$'),
  constraint "ChkP124CategoryItemsArray" check (jsonb_typeof("Items") = 'array')
);

create table if not exists public."TblP124Question" (
  "QuestionID" bigint generated by default as identity primary key,
  "CategoryID" bigint not null references public."TblP124Category"("CategoryID") on delete restrict,
  "TargetItemID" text not null,
  "CorrectItemIDs" jsonb not null default '[]'::jsonb,
  "DistractorItemIDs" jsonb not null default '[]'::jsonb,
  "IsActive" boolean not null default true,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "UqP124QuestionTarget" unique ("CategoryID", "TargetItemID"),
  constraint "ChkP124CorrectArray" check (
    jsonb_typeof("CorrectItemIDs") = 'array' and jsonb_array_length("CorrectItemIDs") > 0
  ),
  constraint "ChkP124DistractorArray" check (jsonb_typeof("DistractorItemIDs") = 'array')
);

comment on table public."TblP124Category" is 'P124 題目分類與完整候選集合';
comment on table public."TblP124Question" is 'P124 題目、正確答案與人工誘答';
